version: "3"

services:
  typo3:
    image: martinhelmich/typo3
    ports:
      - 8080:80

  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "typo3"
