version: "3"

services:
  typo3:
    image: martinhelmich/typo3:6
    ports:
      - 8080:80
    volumes:
      - ./typo3conf:/var/www/html/typo3conf

  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "typo3"
