version: "3"

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
