version: "3"

services:
  drupal:
    image: drupal:7-apache
    ports:
      - 8080:80

  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "drupal"
