version: "3"

services:
  joomla:
    image: joomla
    ports:
      - 8080:80
    links:
      - mysql:mysql
    environment:
      JOOMLA_DB_HOST: mysql:3306
      JOOMLA_DB_PASSWORD: password

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: joomla
